<?php

declare(strict_types=1);

namespace HubSpotSDK\Crm\Imports\PublicImportError;

/**
 * The classification of what went wrong during import processing.
 */
enum ErrorType: string
{
    case AMBIGUOUS_ENUMERATION_OPTION = 'AMBIGUOUS_ENUMERATION_OPTION';

    case ASSOCIATION_LABEL_NOT_FOUND = 'ASSOCIATION_LABEL_NOT_FOUND';

    case ASSOCIATION_LIMIT_EXCEEDED = 'ASSOCIATION_LIMIT_EXCEEDED';

    case ASSOCIATION_RECORD_NOT_FOUND = 'ASSOCIATION_RECORD_NOT_FOUND';

    case COLUMN_TOO_LARGE = 'COLUMN_TOO_LARGE';

    case COULD_NOT_FIND_BUSINESS_UNIT = 'COULD_NOT_FIND_BUSINESS_UNIT';

    case COULD_NOT_FIND_OWNER = 'COULD_NOT_FIND_OWNER';

    case COULD_NOT_PARSE_DATE = 'COULD_NOT_PARSE_DATE';

    case COULD_NOT_PARSE_NUMBER = 'COULD_NOT_PARSE_NUMBER';

    case COULD_NOT_PARSE_ROW = 'COULD_NOT_PARSE_ROW';

    case COULD_NOT_PARSE_TERM = 'COULD_NOT_PARSE_TERM';

    case CREATE_ONLY_IMPORT = 'CREATE_ONLY_IMPORT';

    case DUPLICATE_ALTERNATE_ID = 'DUPLICATE_ALTERNATE_ID';

    case DUPLICATE_ASSOCIATION_ID = 'DUPLICATE_ASSOCIATION_ID';

    case DUPLICATE_EVENT = 'DUPLICATE_EVENT';

    case DUPLICATE_OBJECT_ID = 'DUPLICATE_OBJECT_ID';

    case DUPLICATE_RECORD_ID = 'DUPLICATE_RECORD_ID';

    case DUPLICATE_ROW_CONTENT = 'DUPLICATE_ROW_CONTENT';

    case DUPLICATE_UNIQUE_CREATION_KEY = 'DUPLICATE_UNIQUE_CREATION_KEY';

    case DUPLICATE_UNIQUE_PROPERTY_VALUE = 'DUPLICATE_UNIQUE_PROPERTY_VALUE';

    case FAILED_TO_CREATE_ASSOCIATION = 'FAILED_TO_CREATE_ASSOCIATION';

    case FAILED_TO_FIND_RECORD_FOR_ASSOCIATIONS = 'FAILED_TO_FIND_RECORD_FOR_ASSOCIATIONS';

    case FAILED_TO_OPT_OUT_CONTACT = 'FAILED_TO_OPT_OUT_CONTACT';

    case FAILED_TO_PROCESS_OBJECT_WITH_EMPTY_PROPERTY_VALUES = 'FAILED_TO_PROCESS_OBJECT_WITH_EMPTY_PROPERTY_VALUES';

    case FAILED_VALIDATION = 'FAILED_VALIDATION';

    case FILE_NOT_FOUND = 'FILE_NOT_FOUND';

    case GDPR_BLACKLISTED_EMAIL = 'GDPR_BLACKLISTED_EMAIL';

    case INCORRECT_NUMBER_OF_COLUMNS = 'INCORRECT_NUMBER_OF_COLUMNS';

    case INVALID_ALTERNATE_ID = 'INVALID_ALTERNATE_ID';

    case INVALID_ASSOCIATION_IDENTIFIER = 'INVALID_ASSOCIATION_IDENTIFIER';

    case INVALID_ASSOCIATION_KEY = 'INVALID_ASSOCIATION_KEY';

    case INVALID_COLUMN_CONFIGURATION = 'INVALID_COLUMN_CONFIGURATION';

    case INVALID_CUSTOM_PROPERTY_VALIDATION = 'INVALID_CUSTOM_PROPERTY_VALIDATION';

    case INVALID_DOMAIN = 'INVALID_DOMAIN';

    case INVALID_EMAIL = 'INVALID_EMAIL';

    case INVALID_ENUM_FILE_ID_OR_URL = 'INVALID_ENUM_FILE_ID_OR_URL';

    case INVALID_ENUMERATION_OPTION = 'INVALID_ENUMERATION_OPTION';

    case INVALID_EVENT = 'INVALID_EVENT';

    case INVALID_EVENT_TIMESTAMP = 'INVALID_EVENT_TIMESTAMP';

    case INVALID_FILE_TYPE = 'INVALID_FILE_TYPE';

    case INVALID_NUMBER_SIZE = 'INVALID_NUMBER_SIZE';

    case INVALID_OBJECT_ID = 'INVALID_OBJECT_ID';

    case INVALID_PROPERTY_VALUE_FORMAT = 'INVALID_PROPERTY_VALUE_FORMAT';

    case INVALID_RECORD_ID = 'INVALID_RECORD_ID';

    case INVALID_REQUIRED_PROPERTY = 'INVALID_REQUIRED_PROPERTY';

    case INVALID_SHEET_COUNT = 'INVALID_SHEET_COUNT';

    case INVALID_SPREADSHEET = 'INVALID_SPREADSHEET';

    case LIMIT_EXCEEDED = 'LIMIT_EXCEEDED';

    case MANY_ERRORS_IN_ROW = 'MANY_ERRORS_IN_ROW';

    case MISSING_EVENT_DEFINITION = 'MISSING_EVENT_DEFINITION';

    case MISSING_EVENT_TIMESTAMP = 'MISSING_EVENT_TIMESTAMP';

    case MISSING_OBJECT_DEFINITION = 'MISSING_OBJECT_DEFINITION';

    case MISSING_REQUIRED_PROPERTY = 'MISSING_REQUIRED_PROPERTY';

    case MULTIPLE_COMPANIES_WITH_THIS_DOMAIN = 'MULTIPLE_COMPANIES_WITH_THIS_DOMAIN';

    case MULTIPLE_OWNERS_FOUND = 'MULTIPLE_OWNERS_FOUND';

    case NO_OBJECT_ID_FROM_ASSOCIATION_IDENTIFIER = 'NO_OBJECT_ID_FROM_ASSOCIATION_IDENTIFIER';

    case OUTSIDE_VALID_TERM_RANGE = 'OUTSIDE_VALID_TERM_RANGE';

    case OUTSIDE_VALID_TIME_RANGE = 'OUTSIDE_VALID_TIME_RANGE';

    case PORTAL_WIDE_CUSTOM_OBJECT_LIMIT_EXCEEDED = 'PORTAL_WIDE_CUSTOM_OBJECT_LIMIT_EXCEEDED';

    case PROPERTY_DEFINITION_NOT_FOUND = 'PROPERTY_DEFINITION_NOT_FOUND';

    case PROPERTY_VALUE_NOT_FOUND = 'PROPERTY_VALUE_NOT_FOUND';

    case ROW_DATA_TOO_LARGE = 'ROW_DATA_TOO_LARGE';

    case SECONDARY_EMAIL_WRITE_FAILURE = 'SECONDARY_EMAIL_WRITE_FAILURE';

    case UNKNOWN_ASSOCIATION_RECORD_ID = 'UNKNOWN_ASSOCIATION_RECORD_ID';

    case UNKNOWN_BAD_REQUEST = 'UNKNOWN_BAD_REQUEST';

    case UNKNOWN_ERROR = 'UNKNOWN_ERROR';

    case UPDATE_ONLY_IMPORT = 'UPDATE_ONLY_IMPORT';
}
