<?php

declare(strict_types=1);

namespace HubSpotSDK\Account\Activity\HydratedCriticalAction;

/**
 * The type of activity.
 */
enum Type: string
{
    case ACCEPTANCE_TEST = 'ACCEPTANCE_TEST';

    case ACCOUNT_ADDED_TO_MULTI_ACCOUNT_ORGANIZATION = 'ACCOUNT_ADDED_TO_MULTI_ACCOUNT_ORGANIZATION';

    case ACCOUNT_REMOVED_FROM_MULTI_ACCOUNT_ORGANIZATION = 'ACCOUNT_REMOVED_FROM_MULTI_ACCOUNT_ORGANIZATION';

    case ADD_ADMIN_PERMISSIONS = 'ADD_ADMIN_PERMISSIONS';

    case ADD_ADMIN_USER = 'ADD_ADMIN_USER';

    case ADD_SINGLE_SIGN_ON = 'ADD_SINGLE_SIGN_ON';

    case ADD_TWO_FACTOR_AUTHENTICATION = 'ADD_TWO_FACTOR_AUTHENTICATION';

    case ADD_USER = 'ADD_USER';

    case ADD_WEBHOOK_IN_WORKFLOW = 'ADD_WEBHOOK_IN_WORKFLOW';

    case ALLOWED_GEOLOCATIONS_DISABLED = 'ALLOWED_GEOLOCATIONS_DISABLED';

    case ALLOWED_GEOLOCATIONS_ENABLED = 'ALLOWED_GEOLOCATIONS_ENABLED';

    case ALLOWED_LOGIN_METHODS_DELETE = 'ALLOWED_LOGIN_METHODS_DELETE';

    case ALLOWED_LOGIN_METHODS_UPDATE = 'ALLOWED_LOGIN_METHODS_UPDATE';

    case ATTACHMENT_LOGGING_DISABLED = 'ATTACHMENT_LOGGING_DISABLED';

    case ATTACHMENT_LOGGING_ENABLED = 'ATTACHMENT_LOGGING_ENABLED';

    case AUTOMATED_INACTIVE_USER_DEACTIVATION_DISABLED = 'AUTOMATED_INACTIVE_USER_DEACTIVATION_DISABLED';

    case AUTOMATED_INACTIVE_USER_DEACTIVATION_ENABLED = 'AUTOMATED_INACTIVE_USER_DEACTIVATION_ENABLED';

    case BOTS_WEBHOOK_POST = 'BOTS_WEBHOOK_POST';

    case BOTS_WEBHOOK_UPDATE = 'BOTS_WEBHOOK_UPDATE';

    case BOTS_WEBHOOK_VIEWED = 'BOTS_WEBHOOK_VIEWED';

    case BULK_EMAIL_DOMAIN_CHANGE = 'BULK_EMAIL_DOMAIN_CHANGE';

    case CHANGE_AD_EVENT_CONSENT_SETTING = 'CHANGE_AD_EVENT_CONSENT_SETTING';

    case CHANGE_AD_EVENT_DATA_SHARING_SETTING = 'CHANGE_AD_EVENT_DATA_SHARING_SETTING';

    case CHANGE_PASSWORD = 'CHANGE_PASSWORD';

    case CONTACT_DATA_EXPORT = 'CONTACT_DATA_EXPORT';

    case DATA_ACCESS_REQUEST_SUBMITTED = 'DATA_ACCESS_REQUEST_SUBMITTED';

    case DATA_BACKUP_CREATED = 'DATA_BACKUP_CREATED';

    case DATA_BACKUP_DOWNLOADED = 'DATA_BACKUP_DOWNLOADED';

    case DATA_BACKUP_SCHEDULE_CREATED = 'DATA_BACKUP_SCHEDULE_CREATED';

    case DATA_BACKUP_SCHEDULE_DELETED = 'DATA_BACKUP_SCHEDULE_DELETED';

    case DATA_BACKUP_SCHEDULE_UPDATED = 'DATA_BACKUP_SCHEDULE_UPDATED';

    case DATA_RESTORE_COMPLETED = 'DATA_RESTORE_COMPLETED';

    case DATA_SHARING_CONNECTION_ADDED = 'DATA_SHARING_CONNECTION_ADDED';

    case DATA_SHARING_CONNECTION_REMOVED = 'DATA_SHARING_CONNECTION_REMOVED';

    case DATASET_SYNC = 'DATASET_SYNC';

    case DEACTIVATE_USER = 'DEACTIVATE_USER';

    case DOMAIN_BASED_INVITE_CREATED = 'DOMAIN_BASED_INVITE_CREATED';

    case DOMAIN_BASED_INVITE_REMOVED = 'DOMAIN_BASED_INVITE_REMOVED';

    case DOMAIN_BASED_INVITES_DISABLED = 'DOMAIN_BASED_INVITES_DISABLED';

    case DOMAIN_BASED_INVITES_ENABLED = 'DOMAIN_BASED_INVITES_ENABLED';

    case EMAIL_TRACKING_DISABLED = 'EMAIL_TRACKING_DISABLED';

    case EMAIL_TRACKING_ENABLED = 'EMAIL_TRACKING_ENABLED';

    case EXPORT = 'EXPORT';

    case EXPORT_APPROVAL = 'EXPORT_APPROVAL';

    case EXPORT_DOWNLOAD = 'EXPORT_DOWNLOAD';

    case EXPORT_USERS = 'EXPORT_USERS';

    case FORM_SUBMISSIONS_EXPORT = 'FORM_SUBMISSIONS_EXPORT';

    case GDPR_DELETE = 'GDPR_DELETE';

    case GDPR_TOGGLE_DISABLED = 'GDPR_TOGGLE_DISABLED';

    case GDPR_TOGGLE_ENABLED = 'GDPR_TOGGLE_ENABLED';

    case HAPIKEY_CREATE = 'HAPIKEY_CREATE';

    case HAPIKEY_DEACTIVATE = 'HAPIKEY_DEACTIVATE';

    case HAPIKEY_VIEW = 'HAPIKEY_VIEW';

    case HUBSPOT_EMPLOYEE_ACCESS_DISABLED = 'HUBSPOT_EMPLOYEE_ACCESS_DISABLED';

    case HUBSPOT_EMPLOYEE_ACCESS_ENABLED = 'HUBSPOT_EMPLOYEE_ACCESS_ENABLED';

    case IMPERSONATE_USER = 'IMPERSONATE_USER';

    case IMPORT = 'IMPORT';

    case INSTALL_INTEGRATION = 'INSTALL_INTEGRATION';

    case IP_RESTRICTIONS_DISABLED = 'IP_RESTRICTIONS_DISABLED';

    case IP_RESTRICTIONS_ENABLED = 'IP_RESTRICTIONS_ENABLED';

    case JOINED_PORTAL_VIA_DOMAIN_BASED_INVITE = 'JOINED_PORTAL_VIA_DOMAIN_BASED_INVITE';

    case LEGAL_BASIS_REQUIREMENT_DISABLED = 'LEGAL_BASIS_REQUIREMENT_DISABLED';

    case LEGAL_BASIS_REQUIREMENT_ENABLED = 'LEGAL_BASIS_REQUIREMENT_ENABLED';

    case MANUAL_PASSWORD_RESET_EMAIL_SEND = 'MANUAL_PASSWORD_RESET_EMAIL_SEND';

    case MANUAL_REGISTRATION_EMAIL_SEND = 'MANUAL_REGISTRATION_EMAIL_SEND';

    case MARKETING_CONTACTS_APP_SETTINGS_DISABLED = 'MARKETING_CONTACTS_APP_SETTINGS_DISABLED';

    case MARKETING_CONTACTS_APP_SETTINGS_ENABLED = 'MARKETING_CONTACTS_APP_SETTINGS_ENABLED';

    case MERGE_REVERT = 'MERGE_REVERT';

    case MODIFY_WEBHOOK_IN_WORKFLOW = 'MODIFY_WEBHOOK_IN_WORKFLOW';

    case MULTI_ACCOUNT_REPORTING_CONNECTION_ADDED = 'MULTI_ACCOUNT_REPORTING_CONNECTION_ADDED';

    case MULTI_ACCOUNT_REPORTING_CONNECTION_REMOVED = 'MULTI_ACCOUNT_REPORTING_CONNECTION_REMOVED';

    case MULTI_ACCOUNT_WORKFLOWS_CONNECTION_ADDED = 'MULTI_ACCOUNT_WORKFLOWS_CONNECTION_ADDED';

    case MULTI_ACCOUNT_WORKFLOWS_CONNECTION_REMOVED = 'MULTI_ACCOUNT_WORKFLOWS_CONNECTION_REMOVED';

    case NEVER_LOG_FOR_PORTAL_ADDITION = 'NEVER_LOG_FOR_PORTAL_ADDITION';

    case NEVER_LOG_FOR_PORTAL_DELETION = 'NEVER_LOG_FOR_PORTAL_DELETION';

    case NEVER_LOG_FOR_USER_ADDITION = 'NEVER_LOG_FOR_USER_ADDITION';

    case NEVER_LOG_FOR_USER_DELETION = 'NEVER_LOG_FOR_USER_DELETION';

    case PASSKEY_ADDED = 'PASSKEY_ADDED';

    case PASSKEY_DELETED = 'PASSKEY_DELETED';

    case PAYMENT_ACCOUNT_CREATION = 'PAYMENT_ACCOUNT_CREATION';

    case PAYMENT_ACCOUNT_INFO_UPDATE = 'PAYMENT_ACCOUNT_INFO_UPDATE';

    case PAYMENT_BANK_ACCOUNT_CHANGE = 'PAYMENT_BANK_ACCOUNT_CHANGE';

    case PAYMENT_ONBOARDING_LINK_SEND = 'PAYMENT_ONBOARDING_LINK_SEND';

    case PERSONAL_ACCESS_KEY_CREATE = 'PERSONAL_ACCESS_KEY_CREATE';

    case PERSONAL_ACCESS_KEY_DEACTIVATE = 'PERSONAL_ACCESS_KEY_DEACTIVATE';

    case PERSONAL_ACCESS_KEY_ROTATE = 'PERSONAL_ACCESS_KEY_ROTATE';

    case PERSONAL_ACCESS_KEY_VIEW = 'PERSONAL_ACCESS_KEY_VIEW';

    case PRIVATE_APP_ACCESS_TOKEN_CREATE = 'PRIVATE_APP_ACCESS_TOKEN_CREATE';

    case PRIVATE_APP_ACCESS_TOKEN_DEACTIVATE = 'PRIVATE_APP_ACCESS_TOKEN_DEACTIVATE';

    case PRIVATE_APP_ACCESS_TOKEN_ROTATE = 'PRIVATE_APP_ACCESS_TOKEN_ROTATE';

    case PRIVATE_APP_ACCESS_TOKEN_VIEW = 'PRIVATE_APP_ACCESS_TOKEN_VIEW';

    case PRIVATE_APP_CLIENT_SECRET_VIEW = 'PRIVATE_APP_CLIENT_SECRET_VIEW';

    case PRIVATE_APP_CLIENT_SECRET_WRITE = 'PRIVATE_APP_CLIENT_SECRET_WRITE';

    case PRIVATE_APP_SCOPE_GROUPS_UPDATE = 'PRIVATE_APP_SCOPE_GROUPS_UPDATE';

    case PRODUCTION_DEPLOYMENT = 'PRODUCTION_DEPLOYMENT';

    case PROPERTY_HISTORY_REVISION = 'PROPERTY_HISTORY_REVISION';

    case PUBLIC_APP_CLIENT_SECRET_VIEW = 'PUBLIC_APP_CLIENT_SECRET_VIEW';

    case PUBLIC_APP_CLIENT_SECRET_WRITE = 'PUBLIC_APP_CLIENT_SECRET_WRITE';

    case REACTIVATE_USER = 'REACTIVATE_USER';

    case REMOVE_ADMIN_PERMISSIONS = 'REMOVE_ADMIN_PERMISSIONS';

    case REMOVE_ADMIN_USER = 'REMOVE_ADMIN_USER';

    case REMOVE_SINGLE_SIGN_ON = 'REMOVE_SINGLE_SIGN_ON';

    case REMOVE_TWO_FACTOR_AUTHENTICATION = 'REMOVE_TWO_FACTOR_AUTHENTICATION';

    case REMOVE_USER = 'REMOVE_USER';

    case REQUIRE_SINGLE_SIGN_ON = 'REQUIRE_SINGLE_SIGN_ON';

    case RESTRICTED_LIST_ADDED_TO_CONTENT = 'RESTRICTED_LIST_ADDED_TO_CONTENT';

    case SANDBOX_CREATION = 'SANDBOX_CREATION';

    case SANDBOX_DELETION = 'SANDBOX_DELETION';

    case SANDBOX_SYNC = 'SANDBOX_SYNC';

    case SANDBOX_SYNC_TO_PRODUCTION = 'SANDBOX_SYNC_TO_PRODUCTION';

    case SECRET_ADDED_TO_SERVERLESS_FUNCTION = 'SECRET_ADDED_TO_SERVERLESS_FUNCTION';

    case SENSITIVE_DATA_DISABLED = 'SENSITIVE_DATA_DISABLED';

    case SENSITIVE_DATA_ENABLED = 'SENSITIVE_DATA_ENABLED';

    case SEQUENCE_CLONED = 'SEQUENCE_CLONED';

    case SEQUENCE_CREATED = 'SEQUENCE_CREATED';

    case SEQUENCE_ENROLLMENT_INITIATED = 'SEQUENCE_ENROLLMENT_INITIATED';

    case SEQUENCE_ENROLLMENT_STATE_CHANGED = 'SEQUENCE_ENROLLMENT_STATE_CHANGED';

    case SEQUENCE_MODIFIED = 'SEQUENCE_MODIFIED';

    case SERVICE_KEY_CREATE = 'SERVICE_KEY_CREATE';

    case SERVICE_KEY_DEACTIVATE = 'SERVICE_KEY_DEACTIVATE';

    case SERVICE_KEY_PERMISSIONS_UPDATE = 'SERVICE_KEY_PERMISSIONS_UPDATE';

    case SERVICE_KEY_REVEAL = 'SERVICE_KEY_REVEAL';

    case SERVICE_KEY_ROTATE = 'SERVICE_KEY_ROTATE';

    case SMTP_TOKEN_CREATED = 'SMTP_TOKEN_CREATED';

    case SMTP_TOKEN_DELETED = 'SMTP_TOKEN_DELETED';

    case SMTP_TOKEN_PASSWORD_RESET = 'SMTP_TOKEN_PASSWORD_RESET';

    case SMTP_TOKEN_RETRIEVED = 'SMTP_TOKEN_RETRIEVED';

    case TEAM_ADDED = 'TEAM_ADDED';

    case TEAM_DELETED = 'TEAM_DELETED';

    case TEAM_USER_ADDED = 'TEAM_USER_ADDED';

    case TEAM_USER_DELETED = 'TEAM_USER_DELETED';

    case TEMPLATE_MODIFIED = 'TEMPLATE_MODIFIED';

    case TOUCHLESS_PURCHASE = 'TOUCHLESS_PURCHASE';

    case UNIFIED_RESTORE_UNDO_EXECUTION = 'UNIFIED_RESTORE_UNDO_EXECUTION';

    case UNINSTALL_INTEGRATION = 'UNINSTALL_INTEGRATION';

    case UNREQUIRE_SINGLE_SIGN_ON = 'UNREQUIRE_SINGLE_SIGN_ON';

    case WEBHOOK_SETTINGS_UPDATE = 'WEBHOOK_SETTINGS_UPDATE';

    case WEBHOOK_SUBSCRIPTION_CREATE = 'WEBHOOK_SUBSCRIPTION_CREATE';

    case WEBHOOK_SUBSCRIPTION_UPDATE = 'WEBHOOK_SUBSCRIPTION_UPDATE';
}
