<?php

declare(strict_types=1);

namespace HubspotSDK\Marketing\Emails\EmailListParams;

enum Type: string
{
    case AB_EMAIL = 'AB_EMAIL';

    case AUTOMATED_AB_EMAIL = 'AUTOMATED_AB_EMAIL';

    case AUTOMATED_EMAIL = 'AUTOMATED_EMAIL';

    case BATCH_EMAIL = 'BATCH_EMAIL';

    case BLOG_EMAIL = 'BLOG_EMAIL';

    case BLOG_EMAIL_CHILD = 'BLOG_EMAIL_CHILD';

    case FEEDBACK_CES_EMAIL = 'FEEDBACK_CES_EMAIL';

    case FEEDBACK_CUSTOM_EMAIL = 'FEEDBACK_CUSTOM_EMAIL';

    case FEEDBACK_CUSTOM_SURVEY_EMAIL = 'FEEDBACK_CUSTOM_SURVEY_EMAIL';

    case FEEDBACK_NPS_EMAIL = 'FEEDBACK_NPS_EMAIL';

    case FOLLOWUP_EMAIL = 'FOLLOWUP_EMAIL';

    case LEADFLOW_EMAIL = 'LEADFLOW_EMAIL';

    case LOCALTIME_EMAIL = 'LOCALTIME_EMAIL';

    case MANAGE_PREFERENCES_EMAIL = 'MANAGE_PREFERENCES_EMAIL';

    case MARKETING_SINGLE_SEND_API = 'MARKETING_SINGLE_SEND_API';

    case MEMBERSHIP_EMAIL_VERIFICATION_EMAIL = 'MEMBERSHIP_EMAIL_VERIFICATION_EMAIL';

    case MEMBERSHIP_FOLLOW_UP_EMAIL = 'MEMBERSHIP_FOLLOW_UP_EMAIL';

    case MEMBERSHIP_OTP_LOGIN_EMAIL = 'MEMBERSHIP_OTP_LOGIN_EMAIL';

    case MEMBERSHIP_PASSWORD_RESET_EMAIL = 'MEMBERSHIP_PASSWORD_RESET_EMAIL';

    case MEMBERSHIP_PASSWORD_SAVED_EMAIL = 'MEMBERSHIP_PASSWORD_SAVED_EMAIL';

    case MEMBERSHIP_PASSWORDLESS_AUTH_EMAIL = 'MEMBERSHIP_PASSWORDLESS_AUTH_EMAIL';

    case MEMBERSHIP_REGISTRATION_EMAIL = 'MEMBERSHIP_REGISTRATION_EMAIL';

    case MEMBERSHIP_REGISTRATION_FOLLOW_UP_EMAIL = 'MEMBERSHIP_REGISTRATION_FOLLOW_UP_EMAIL';

    case MEMBERSHIP_VERIFICATION_EMAIL = 'MEMBERSHIP_VERIFICATION_EMAIL';

    case OPTIN_EMAIL = 'OPTIN_EMAIL';

    case OPTIN_FOLLOWUP_EMAIL = 'OPTIN_FOLLOWUP_EMAIL';

    case RESUBSCRIBE_EMAIL = 'RESUBSCRIBE_EMAIL';

    case RSS_EMAIL = 'RSS_EMAIL';

    case RSS_EMAIL_CHILD = 'RSS_EMAIL_CHILD';

    case SINGLE_SEND_API = 'SINGLE_SEND_API';

    case SMTP_TOKEN = 'SMTP_TOKEN';

    case TICKET_EMAIL = 'TICKET_EMAIL';
}
