<?php

declare(strict_types=1);

namespace HubspotSDK\Crm\Pipelines;

use HubspotSDK\Core\Attributes\Api;
use HubspotSDK\Core\Concerns\SdkModel;
use HubspotSDK\Core\Contracts\BaseModel;
use HubspotSDK\Crm\Pipelines\PipelineStage\WritePermissions;

/**
 * A pipeline stage definition.
 *
 * @phpstan-type PipelineStageShape = array{
 *   id: string,
 *   archived: bool,
 *   createdAt: \DateTimeInterface,
 *   displayOrder: int,
 *   label: string,
 *   updatedAt: \DateTimeInterface,
 *   archivedAt?: \DateTimeInterface|null,
 *   metadata?: array<string,string>|null,
 *   writePermissions?: value-of<WritePermissions>|null,
 * }
 */
final class PipelineStage implements BaseModel
{
    /** @use SdkModel<PipelineStageShape> */
    use SdkModel;

    /**
     * A unique identifier generated by HubSpot that can be used to retrieve and update the pipeline stage.
     */
    #[Api]
    public string $id;

    /**
     * Whether the pipeline is archived.
     */
    #[Api]
    public bool $archived;

    /**
     * The date the pipeline stage was created. The stages on default pipelines will have createdAt = 0.
     */
    #[Api]
    public \DateTimeInterface $createdAt;

    /**
     * The order for displaying this pipeline stage. If two pipeline stages have a matching `displayOrder`, they will be sorted alphabetically by label.
     */
    #[Api]
    public int $displayOrder;

    /**
     * A label used to organize pipeline stages in HubSpot's UI. Each pipeline stage's label must be unique within that pipeline.
     */
    #[Api]
    public string $label;

    /**
     * The date the pipeline stage was last updated.
     */
    #[Api]
    public \DateTimeInterface $updatedAt;

    /**
     * The date the pipeline was archived. `archivedAt` will only be present if the pipeline is archived.
     */
    #[Api(optional: true)]
    public ?\DateTimeInterface $archivedAt;

    /**
     * A JSON object containing properties that are not present on all object pipelines.
     *
     * For `deals` pipelines, the `probability` field is required (`{ "probability": 0.5 }`), and represents the likelihood a deal will close. Possible values are between 0.0 and 1.0 in increments of 0.1.
     *
     * For `tickets` pipelines, the `ticketState` field is optional (`{ "ticketState": "OPEN" }`), and represents whether the ticket remains open or has been closed by a member of your Support team. Possible values are `OPEN` or `CLOSED`.
     *
     * @var array<string,string>|null $metadata
     */
    #[Api(map: 'string', optional: true)]
    public ?array $metadata;

    /**
     * Defines the level of write access for the pipeline stage, with possible values being CRM_PERMISSIONS_ENFORCEMENT, READ_ONLY, or INTERNAL_ONLY.
     *
     * @var value-of<WritePermissions>|null $writePermissions
     */
    #[Api(enum: WritePermissions::class, optional: true)]
    public ?string $writePermissions;

    /**
     * `new PipelineStage()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * PipelineStage::with(
     *   id: ...,
     *   archived: ...,
     *   createdAt: ...,
     *   displayOrder: ...,
     *   label: ...,
     *   updatedAt: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new PipelineStage)
     *   ->withID(...)
     *   ->withArchived(...)
     *   ->withCreatedAt(...)
     *   ->withDisplayOrder(...)
     *   ->withLabel(...)
     *   ->withUpdatedAt(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param array<string,string> $metadata
     * @param WritePermissions|value-of<WritePermissions> $writePermissions
     */
    public static function with(
        string $id,
        bool $archived,
        \DateTimeInterface $createdAt,
        int $displayOrder,
        string $label,
        \DateTimeInterface $updatedAt,
        ?\DateTimeInterface $archivedAt = null,
        ?array $metadata = null,
        WritePermissions|string|null $writePermissions = null,
    ): self {
        $obj = new self;

        $obj->id = $id;
        $obj->archived = $archived;
        $obj->createdAt = $createdAt;
        $obj->displayOrder = $displayOrder;
        $obj->label = $label;
        $obj->updatedAt = $updatedAt;

        null !== $archivedAt && $obj->archivedAt = $archivedAt;
        null !== $metadata && $obj->metadata = $metadata;
        null !== $writePermissions && $obj['writePermissions'] = $writePermissions;

        return $obj;
    }

    /**
     * A unique identifier generated by HubSpot that can be used to retrieve and update the pipeline stage.
     */
    public function withID(string $id): self
    {
        $obj = clone $this;
        $obj->id = $id;

        return $obj;
    }

    /**
     * Whether the pipeline is archived.
     */
    public function withArchived(bool $archived): self
    {
        $obj = clone $this;
        $obj->archived = $archived;

        return $obj;
    }

    /**
     * The date the pipeline stage was created. The stages on default pipelines will have createdAt = 0.
     */
    public function withCreatedAt(\DateTimeInterface $createdAt): self
    {
        $obj = clone $this;
        $obj->createdAt = $createdAt;

        return $obj;
    }

    /**
     * The order for displaying this pipeline stage. If two pipeline stages have a matching `displayOrder`, they will be sorted alphabetically by label.
     */
    public function withDisplayOrder(int $displayOrder): self
    {
        $obj = clone $this;
        $obj->displayOrder = $displayOrder;

        return $obj;
    }

    /**
     * A label used to organize pipeline stages in HubSpot's UI. Each pipeline stage's label must be unique within that pipeline.
     */
    public function withLabel(string $label): self
    {
        $obj = clone $this;
        $obj->label = $label;

        return $obj;
    }

    /**
     * The date the pipeline stage was last updated.
     */
    public function withUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $obj = clone $this;
        $obj->updatedAt = $updatedAt;

        return $obj;
    }

    /**
     * The date the pipeline was archived. `archivedAt` will only be present if the pipeline is archived.
     */
    public function withArchivedAt(\DateTimeInterface $archivedAt): self
    {
        $obj = clone $this;
        $obj->archivedAt = $archivedAt;

        return $obj;
    }

    /**
     * A JSON object containing properties that are not present on all object pipelines.
     *
     * For `deals` pipelines, the `probability` field is required (`{ "probability": 0.5 }`), and represents the likelihood a deal will close. Possible values are between 0.0 and 1.0 in increments of 0.1.
     *
     * For `tickets` pipelines, the `ticketState` field is optional (`{ "ticketState": "OPEN" }`), and represents whether the ticket remains open or has been closed by a member of your Support team. Possible values are `OPEN` or `CLOSED`.
     *
     * @param array<string,string> $metadata
     */
    public function withMetadata(array $metadata): self
    {
        $obj = clone $this;
        $obj->metadata = $metadata;

        return $obj;
    }

    /**
     * Defines the level of write access for the pipeline stage, with possible values being CRM_PERMISSIONS_ENFORCEMENT, READ_ONLY, or INTERNAL_ONLY.
     *
     * @param WritePermissions|value-of<WritePermissions> $writePermissions
     */
    public function withWritePermissions(
        WritePermissions|string $writePermissions
    ): self {
        $obj = clone $this;
        $obj['writePermissions'] = $writePermissions;

        return $obj;
    }
}
