<?php

declare(strict_types=1);

namespace HubspotSDK\Crm\Pipelines;

use HubspotSDK\Core\Attributes\Optional;
use HubspotSDK\Core\Attributes\Required;
use HubspotSDK\Core\Concerns\SdkModel;
use HubspotSDK\Core\Contracts\BaseModel;
use HubspotSDK\Crm\Pipelines\PipelineStage\WritePermissions;

/**
 * A pipeline definition.
 *
 * @phpstan-type PipelineShape = array{
 *   id: string,
 *   archived: bool,
 *   createdAt: \DateTimeInterface,
 *   displayOrder: int,
 *   label: string,
 *   stages: list<PipelineStage>,
 *   updatedAt: \DateTimeInterface,
 *   archivedAt?: \DateTimeInterface|null,
 * }
 */
final class Pipeline implements BaseModel
{
    /** @use SdkModel<PipelineShape> */
    use SdkModel;

    /**
     * A unique identifier generated by HubSpot that can be used to retrieve and update the pipeline.
     */
    #[Required]
    public string $id;

    /**
     * Whether the pipeline is archived.
     */
    #[Required]
    public bool $archived;

    /**
     * The date the pipeline was created. The default pipelines will have createdAt = 0.
     */
    #[Required]
    public \DateTimeInterface $createdAt;

    /**
     * The order for displaying this pipeline. If two pipelines have a matching `displayOrder`, they will be sorted alphabetically by label.
     */
    #[Required]
    public int $displayOrder;

    /**
     * A unique label used to organize pipelines in HubSpot's UI.
     */
    #[Required]
    public string $label;

    /**
     * The stages associated with the pipeline. They can be retrieved and updated via the pipeline stages endpoints.
     *
     * @var list<PipelineStage> $stages
     */
    #[Required(list: PipelineStage::class)]
    public array $stages;

    /**
     * The date the pipeline was last updated.
     */
    #[Required]
    public \DateTimeInterface $updatedAt;

    /**
     * The date the pipeline was archived. `archivedAt` will only be present if the pipeline is archived.
     */
    #[Optional]
    public ?\DateTimeInterface $archivedAt;

    /**
     * `new Pipeline()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * Pipeline::with(
     *   id: ...,
     *   archived: ...,
     *   createdAt: ...,
     *   displayOrder: ...,
     *   label: ...,
     *   stages: ...,
     *   updatedAt: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new Pipeline)
     *   ->withID(...)
     *   ->withArchived(...)
     *   ->withCreatedAt(...)
     *   ->withDisplayOrder(...)
     *   ->withLabel(...)
     *   ->withStages(...)
     *   ->withUpdatedAt(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param list<PipelineStage|array{
     *   id: string,
     *   archived: bool,
     *   createdAt: \DateTimeInterface,
     *   displayOrder: int,
     *   label: string,
     *   metadata: array<string,string>,
     *   updatedAt: \DateTimeInterface,
     *   archivedAt?: \DateTimeInterface|null,
     *   writePermissions?: value-of<WritePermissions>|null,
     * }> $stages
     */
    public static function with(
        string $id,
        bool $archived,
        \DateTimeInterface $createdAt,
        int $displayOrder,
        string $label,
        array $stages,
        \DateTimeInterface $updatedAt,
        ?\DateTimeInterface $archivedAt = null,
    ): self {
        $obj = new self;

        $obj['id'] = $id;
        $obj['archived'] = $archived;
        $obj['createdAt'] = $createdAt;
        $obj['displayOrder'] = $displayOrder;
        $obj['label'] = $label;
        $obj['stages'] = $stages;
        $obj['updatedAt'] = $updatedAt;

        null !== $archivedAt && $obj['archivedAt'] = $archivedAt;

        return $obj;
    }

    /**
     * A unique identifier generated by HubSpot that can be used to retrieve and update the pipeline.
     */
    public function withID(string $id): self
    {
        $obj = clone $this;
        $obj['id'] = $id;

        return $obj;
    }

    /**
     * Whether the pipeline is archived.
     */
    public function withArchived(bool $archived): self
    {
        $obj = clone $this;
        $obj['archived'] = $archived;

        return $obj;
    }

    /**
     * The date the pipeline was created. The default pipelines will have createdAt = 0.
     */
    public function withCreatedAt(\DateTimeInterface $createdAt): self
    {
        $obj = clone $this;
        $obj['createdAt'] = $createdAt;

        return $obj;
    }

    /**
     * The order for displaying this pipeline. If two pipelines have a matching `displayOrder`, they will be sorted alphabetically by label.
     */
    public function withDisplayOrder(int $displayOrder): self
    {
        $obj = clone $this;
        $obj['displayOrder'] = $displayOrder;

        return $obj;
    }

    /**
     * A unique label used to organize pipelines in HubSpot's UI.
     */
    public function withLabel(string $label): self
    {
        $obj = clone $this;
        $obj['label'] = $label;

        return $obj;
    }

    /**
     * The stages associated with the pipeline. They can be retrieved and updated via the pipeline stages endpoints.
     *
     * @param list<PipelineStage|array{
     *   id: string,
     *   archived: bool,
     *   createdAt: \DateTimeInterface,
     *   displayOrder: int,
     *   label: string,
     *   metadata: array<string,string>,
     *   updatedAt: \DateTimeInterface,
     *   archivedAt?: \DateTimeInterface|null,
     *   writePermissions?: value-of<WritePermissions>|null,
     * }> $stages
     */
    public function withStages(array $stages): self
    {
        $obj = clone $this;
        $obj['stages'] = $stages;

        return $obj;
    }

    /**
     * The date the pipeline was last updated.
     */
    public function withUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $obj = clone $this;
        $obj['updatedAt'] = $updatedAt;

        return $obj;
    }

    /**
     * The date the pipeline was archived. `archivedAt` will only be present if the pipeline is archived.
     */
    public function withArchivedAt(\DateTimeInterface $archivedAt): self
    {
        $obj = clone $this;
        $obj['archivedAt'] = $archivedAt;

        return $obj;
    }
}
