<?php

declare(strict_types=1);

namespace HubspotSDK\Marketing\Campaigns;

use HubspotSDK\Core\Attributes\Required;
use HubspotSDK\Core\Concerns\SdkModel;
use HubspotSDK\Core\Contracts\BaseModel;

/**
 * @phpstan-type MetricsCountersShape = array{
 *   influencedContacts: int,
 *   newContactsFirstTouch: int,
 *   newContactsLastTouch: int,
 *   sessions: int,
 * }
 */
final class MetricsCounters implements BaseModel
{
    /** @use SdkModel<MetricsCountersShape> */
    use SdkModel;

    /**
     * The number of contacts influenced by the campaign.
     */
    #[Required]
    public int $influencedContacts;

    /**
     * The number of new contacts attributed to the campaign as the first touchpoint.
     */
    #[Required]
    public int $newContactsFirstTouch;

    /**
     * The number of new contacts attributed to the campaign as the last touchpoint.
     */
    #[Required]
    public int $newContactsLastTouch;

    /**
     * The total number of sessions generated by the campaign.
     */
    #[Required]
    public int $sessions;

    /**
     * `new MetricsCounters()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * MetricsCounters::with(
     *   influencedContacts: ...,
     *   newContactsFirstTouch: ...,
     *   newContactsLastTouch: ...,
     *   sessions: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new MetricsCounters)
     *   ->withInfluencedContacts(...)
     *   ->withNewContactsFirstTouch(...)
     *   ->withNewContactsLastTouch(...)
     *   ->withSessions(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        int $influencedContacts,
        int $newContactsFirstTouch,
        int $newContactsLastTouch,
        int $sessions,
    ): self {
        $self = new self;

        $self['influencedContacts'] = $influencedContacts;
        $self['newContactsFirstTouch'] = $newContactsFirstTouch;
        $self['newContactsLastTouch'] = $newContactsLastTouch;
        $self['sessions'] = $sessions;

        return $self;
    }

    /**
     * The number of contacts influenced by the campaign.
     */
    public function withInfluencedContacts(int $influencedContacts): self
    {
        $self = clone $this;
        $self['influencedContacts'] = $influencedContacts;

        return $self;
    }

    /**
     * The number of new contacts attributed to the campaign as the first touchpoint.
     */
    public function withNewContactsFirstTouch(int $newContactsFirstTouch): self
    {
        $self = clone $this;
        $self['newContactsFirstTouch'] = $newContactsFirstTouch;

        return $self;
    }

    /**
     * The number of new contacts attributed to the campaign as the last touchpoint.
     */
    public function withNewContactsLastTouch(int $newContactsLastTouch): self
    {
        $self = clone $this;
        $self['newContactsLastTouch'] = $newContactsLastTouch;

        return $self;
    }

    /**
     * The total number of sessions generated by the campaign.
     */
    public function withSessions(int $sessions): self
    {
        $self = clone $this;
        $self['sessions'] = $sessions;

        return $self;
    }
}
