<?php

declare(strict_types=1);

namespace HubSpotSDK\Marketing\EmailSendStatusView;

/**
 * Result of the send.
 */
enum SendResult: string
{
    case ADDRESS_LIST_BOMBED = 'ADDRESS_LIST_BOMBED';

    case ADDRESS_ONLY_ACCEPTED_ON_PROD = 'ADDRESS_ONLY_ACCEPTED_ON_PROD';

    case ADDRESS_OPTED_OUT = 'ADDRESS_OPTED_OUT';

    case ATTACHMENT_DOWNLOAD_QUEUE_FULL = 'ATTACHMENT_DOWNLOAD_QUEUE_FULL';

    case BLOCKED_ADDRESS = 'BLOCKED_ADDRESS';

    case BLOCKED_DOMAIN = 'BLOCKED_DOMAIN';

    case BRAND_RECIPIENT_FATIGUE_SUPPRESSED = 'BRAND_RECIPIENT_FATIGUE_SUPPRESSED';

    case CAMPAIGN_CANCELLED = 'CAMPAIGN_CANCELLED';

    case CANCELLED_ABUSE = 'CANCELLED_ABUSE';

    case CORRUPT_INPUT = 'CORRUPT_INPUT';

    case EMAIL_DISABLED = 'EMAIL_DISABLED';

    case EMAIL_UNCONFIRMED = 'EMAIL_UNCONFIRMED';

    case GDPR_DOI_ENABLED = 'GDPR_DOI_ENABLED';

    case GRAYMAIL_SUPPRESSED = 'GRAYMAIL_SUPPRESSED';

    case HUBL_LIMIT_EXCEEDED = 'HUBL_LIMIT_EXCEEDED';

    case IDEMPOTENT_FAIL = 'IDEMPOTENT_FAIL';

    case IDEMPOTENT_IGNORE = 'IDEMPOTENT_IGNORE';

    case INVALID_APP_ID_ATTRIBUTION = 'INVALID_APP_ID_ATTRIBUTION';

    case INVALID_FROM_ADDRESS = 'INVALID_FROM_ADDRESS';

    case INVALID_TO_ADDRESS = 'INVALID_TO_ADDRESS';

    case LOW_CONTACT_QUALITY_SCORE = 'LOW_CONTACT_QUALITY_SCORE';

    case MISSING_CONTENT = 'MISSING_CONTENT';

    case MISSING_REQUIRED_PARAMETER = 'MISSING_REQUIRED_PARAMETER';

    case MISSING_TEMPLATE_PROPERTIES = 'MISSING_TEMPLATE_PROPERTIES';

    case MTA_IGNORE = 'MTA_IGNORE';

    case NON_MARKETABLE_CONTACT = 'NON_MARKETABLE_CONTACT';

    case PORTAL_AUTHENTICATION_FAILURE = 'PORTAL_AUTHENTICATION_FAILURE';

    case PORTAL_EXPIRED = 'PORTAL_EXPIRED';

    case PORTAL_MISSING_MARKETING_SCOPE = 'PORTAL_MISSING_MARKETING_SCOPE';

    case PORTAL_NOT_AUTHORIZED_FOR_APPLICATION = 'PORTAL_NOT_AUTHORIZED_FOR_APPLICATION';

    case PORTAL_OVER_LIMIT = 'PORTAL_OVER_LIMIT';

    case PORTAL_SUSPENDED = 'PORTAL_SUSPENDED';

    case PREVIOUS_SPAM = 'PREVIOUS_SPAM';

    case PREVIOUSLY_BOUNCED = 'PREVIOUSLY_BOUNCED';

    case PREVIOUSLY_UNSUBSCRIBED_BRAND = 'PREVIOUSLY_UNSUBSCRIBED_BRAND';

    case PREVIOUSLY_UNSUBSCRIBED_BUSINESS_UNIT = 'PREVIOUSLY_UNSUBSCRIBED_BUSINESS_UNIT';

    case PREVIOUSLY_UNSUBSCRIBED_MESSAGE = 'PREVIOUSLY_UNSUBSCRIBED_MESSAGE';

    case PREVIOUSLY_UNSUBSCRIBED_PORTAL = 'PREVIOUSLY_UNSUBSCRIBED_PORTAL';

    case QUARANTINED_ADDRESS = 'QUARANTINED_ADDRESS';

    case QUEUED = 'QUEUED';

    case RECIPIENT_FATIGUE_SUPPRESSED = 'RECIPIENT_FATIGUE_SUPPRESSED';

    case SENT = 'SENT';

    case TEMPLATE_RENDER_EXCEPTION = 'TEMPLATE_RENDER_EXCEPTION';

    case THROTTLED = 'THROTTLED';

    case TOO_MANY_RECIPIENTS = 'TOO_MANY_RECIPIENTS';

    case UBB_GOVERNANCE_MISSING = 'UBB_GOVERNANCE_MISSING';

    case UNCONFIGURED_SENDING_DOMAIN = 'UNCONFIGURED_SENDING_DOMAIN';

    case UNDELIVERABLE = 'UNDELIVERABLE';

    case VALIDATION_FAILED = 'VALIDATION_FAILED';
}
