<?php

declare(strict_types=1);

namespace HubspotSDK\Cms\Blogs\Posts\BlogPost;

/**
 * A generated ENUM descibing the current state of this Blog Post. Should always match state.
 */
enum CurrentState: string
{
    case AUTOMATED = 'AUTOMATED';

    case AUTOMATED_AB = 'AUTOMATED_AB';

    case AUTOMATED_AB_VARIANT = 'AUTOMATED_AB_VARIANT';

    case AUTOMATED_DRAFT = 'AUTOMATED_DRAFT';

    case AUTOMATED_DRAFT_AB = 'AUTOMATED_DRAFT_AB';

    case AUTOMATED_DRAFT_ABVARIANT = 'AUTOMATED_DRAFT_ABVARIANT';

    case AUTOMATED_FOR_FORM = 'AUTOMATED_FOR_FORM';

    case AUTOMATED_FOR_FORM_BUFFER = 'AUTOMATED_FOR_FORM_BUFFER';

    case AUTOMATED_FOR_FORM_DRAFT = 'AUTOMATED_FOR_FORM_DRAFT';

    case AUTOMATED_FOR_FORM_LEGACY = 'AUTOMATED_FOR_FORM_LEGACY';

    case AUTOMATED_LOSER_ABVARIANT = 'AUTOMATED_LOSER_ABVARIANT';

    case AUTOMATED_SENDING = 'AUTOMATED_SENDING';

    case BLOG_EMAIL_DRAFT = 'BLOG_EMAIL_DRAFT';

    case BLOG_EMAIL_PUBLISHED = 'BLOG_EMAIL_PUBLISHED';

    case DRAFT = 'DRAFT';

    case DRAFT_AB = 'DRAFT_AB';

    case DRAFT_AB_VARIANT = 'DRAFT_AB_VARIANT';

    case ERROR = 'ERROR';

    case LOSER_AB_VARIANT = 'LOSER_AB_VARIANT';

    case PAGE_STUB = 'PAGE_STUB';

    case PRE_PROCESSING = 'PRE_PROCESSING';

    case PROCESSING = 'PROCESSING';

    case PUBLISHED = 'PUBLISHED';

    case PUBLISHED_AB = 'PUBLISHED_AB';

    case PUBLISHED_AB_VARIANT = 'PUBLISHED_AB_VARIANT';

    case PUBLISHED_OR_SCHEDULED = 'PUBLISHED_OR_SCHEDULED';

    case RSS_TO_EMAIL_DRAFT = 'RSS_TO_EMAIL_DRAFT';

    case RSS_TO_EMAIL_PUBLISHED = 'RSS_TO_EMAIL_PUBLISHED';

    case SCHEDULED = 'SCHEDULED';

    case SCHEDULED_AB = 'SCHEDULED_AB';

    case SCHEDULED_OR_PUBLISHED = 'SCHEDULED_OR_PUBLISHED';
}
