<?php

declare(strict_types=1);

namespace HubSpotSDK\Crm\PropertiesValidations\PropertiesValidationUpdateByObjectTypeIDPropertyNameAndRuleTypeParams;

enum RuleType: string
{
    case AFTER_DATETIME_DURATION = 'AFTER_DATETIME_DURATION';

    case AFTER_DURATION = 'AFTER_DURATION';

    case ALPHANUMERIC = 'ALPHANUMERIC';

    case BEFORE_DATETIME_DURATION = 'BEFORE_DATETIME_DURATION';

    case BEFORE_DURATION = 'BEFORE_DURATION';

    case DAYS_OF_WEEK = 'DAYS_OF_WEEK';

    case DECIMAL = 'DECIMAL';

    case DOMAIN = 'DOMAIN';

    case EMAIL = 'EMAIL';

    case EMAIL_ALLOWED_DOMAINS = 'EMAIL_ALLOWED_DOMAINS';

    case EMAIL_BLOCKED_DOMAINS = 'EMAIL_BLOCKED_DOMAINS';

    case END_DATE = 'END_DATE';

    case END_DATETIME = 'END_DATETIME';

    case FORMAT = 'FORMAT';

    case MAX_LENGTH = 'MAX_LENGTH';

    case MAX_NUMBER = 'MAX_NUMBER';

    case MIN_LENGTH = 'MIN_LENGTH';

    case MIN_NUMBER = 'MIN_NUMBER';

    case PHONE_NUMBER_WITH_EXPLICIT_COUNTRY_CODE = 'PHONE_NUMBER_WITH_EXPLICIT_COUNTRY_CODE';

    case REGEX = 'REGEX';

    case SPECIAL_CHARACTERS = 'SPECIAL_CHARACTERS';

    case START_DATE = 'START_DATE';

    case START_DATETIME = 'START_DATETIME';

    case URL = 'URL';

    case URL_ALLOWED_DOMAINS = 'URL_ALLOWED_DOMAINS';

    case URL_BLOCKED_DOMAINS = 'URL_BLOCKED_DOMAINS';

    case WHITESPACE = 'WHITESPACE';
}
