<?php

declare(strict_types=1);

namespace HubspotSDK\Crm\Imports\PropertyValue;

/**
 * The origin of the property value, such as "IMPORT" or "API".
 */
enum Source: string
{
    case ACADEMY = 'ACADEMY';

    case ACCEPTANCE_TEST = 'ACCEPTANCE_TEST';

    case ADS = 'ADS';

    case AI_GROUP = 'AI_GROUP';

    case ANALYTICS = 'ANALYTICS';

    case API = 'API';

    case APPROVALS = 'APPROVALS';

    case ASSISTS = 'ASSISTS';

    case ASSOCIATIONS = 'ASSOCIATIONS';

    case AUTOMATION_JOURNEY = 'AUTOMATION_JOURNEY';

    case AUTOMATION_PLATFORM = 'AUTOMATION_PLATFORM';

    case AVATARS_SERVICE = 'AVATARS_SERVICE';

    case BATCH_UPDATE = 'BATCH_UPDATE';

    case BCC_TO_CRM = 'BCC_TO_CRM';

    case BEHAVIORAL_EVENTS = 'BEHAVIORAL_EVENTS';

    case BET_ASSIGNMENT = 'BET_ASSIGNMENT';

    case BET_CRM_CONNECTOR = 'BET_CRM_CONNECTOR';

    case BIDEN = 'BIDEN';

    case BILLING = 'BILLING';

    case BOT = 'BOT';

    case CALCULATED = 'CALCULATED';

    case CHATSPOT = 'CHATSPOT';

    case COMMUNICATOR = 'COMMUNICATOR';

    case COMPANIES = 'COMPANIES';

    case COMPANY_FAMILIES = 'COMPANY_FAMILIES';

    case COMPANY_INSIGHTS = 'COMPANY_INSIGHTS';

    case CONTACTS = 'CONTACTS';

    case CONTACTS_WEB = 'CONTACTS_WEB';

    case CONTENT_MEMBERSHIP = 'CONTENT_MEMBERSHIP';

    case CONVERSATIONS = 'CONVERSATIONS';

    case CRM_UI = 'CRM_UI';

    case CRM_UI_BULK_ACTION = 'CRM_UI_BULK_ACTION';

    case DATA_ENRICHMENT = 'DATA_ENRICHMENT';

    case DEALS = 'DEALS';

    case DEFAULT = 'DEFAULT';

    case EMAIL = 'EMAIL';

    case EMAIL_INTEGRATION = 'EMAIL_INTEGRATION';

    case ENGAGEMENTS = 'ENGAGEMENTS';

    case EXTENSION = 'EXTENSION';

    case FILE_MANAGER = 'FILE_MANAGER';

    case FLYWHEEL_PRODUCT_DATA_SYNC = 'FLYWHEEL_PRODUCT_DATA_SYNC';

    case FORECASTING = 'FORECASTING';

    case FORM = 'FORM';

    case FORWARD_TO_CRM = 'FORWARD_TO_CRM';

    case GMAIL_INTEGRATION = 'GMAIL_INTEGRATION';

    case GOALS = 'GOALS';

    case HEISENBERG = 'HEISENBERG';

    case HELP_DESK = 'HELP_DESK';

    case IMPORT = 'IMPORT';

    case INTEGRATION = 'INTEGRATION';

    case INTEGRATIONS_PLATFORM = 'INTEGRATIONS_PLATFORM';

    case INTEGRATIONS_SYNC = 'INTEGRATIONS_SYNC';

    case INTENT = 'INTENT';

    case INTERNAL_PROCESSING = 'INTERNAL_PROCESSING';

    case LEADIN = 'LEADIN';

    case MARKETPLACE = 'MARKETPLACE';

    case MEETINGS = 'MEETINGS';

    case MERGE_COMPANIES = 'MERGE_COMPANIES';

    case MERGE_CONTACTS = 'MERGE_CONTACTS';

    case MERGE_OBJECTS = 'MERGE_OBJECTS';

    case MICROAPPS = 'MICROAPPS';

    case MIGRATION = 'MIGRATION';

    case MOBILE_ANDROID = 'MOBILE_ANDROID';

    case MOBILE_IOS = 'MOBILE_IOS';

    case PAYMENTS = 'PAYMENTS';

    case PIPELINE_SETTINGS = 'PIPELINE_SETTINGS';

    case PLAYBOOKS = 'PLAYBOOKS';

    case PORTAL_OBJECT_SYNC = 'PORTAL_OBJECT_SYNC';

    case PORTAL_USER_ASSOCIATOR = 'PORTAL_USER_ASSOCIATOR';

    case PRESENTATIONS = 'PRESENTATIONS';

    case PROPERTY_SETTINGS = 'PROPERTY_SETTINGS';

    case PROSPECTING_AGENT = 'PROSPECTING_AGENT';

    case QUOTAS = 'QUOTAS';

    case QUOTES = 'QUOTES';

    case RECYCLING_BIN = 'RECYCLING_BIN';

    case SALES = 'SALES';

    case SALES_MESSAGES = 'SALES_MESSAGES';

    case SALESFORCE = 'SALESFORCE';

    case SEQUENCES = 'SEQUENCES';

    case SETTINGS = 'SETTINGS';

    case SIDEKICK = 'SIDEKICK';

    case SIGNALS = 'SIGNALS';

    case SLACK_INTEGRATION = 'SLACK_INTEGRATION';

    case SOCIAL = 'SOCIAL';

    case SUCCESS = 'SUCCESS';

    case TALLY = 'TALLY';

    case TASK = 'TASK';

    case UNKNOWN = 'UNKNOWN';

    case WAL_INCREMENTAL = 'WAL_INCREMENTAL';

    case WORKFLOW_CONTACT_DELETE_ACTION = 'WORKFLOW_CONTACT_DELETE_ACTION';

    case WORKFLOWS = 'WORKFLOWS';
}
