<?php

declare(strict_types=1);

namespace HubspotSDK\Automation\Actions\AutomationActionsFieldTypeDefinition;

enum ReferencedObjectType: string
{
    case CONTACT = 'CONTACT';

    case COMPANY = 'COMPANY';

    case DEAL = 'DEAL';

    case ENGAGEMENT = 'ENGAGEMENT';

    case TICKET = 'TICKET';

    case OWNER = 'OWNER';

    case PRODUCT = 'PRODUCT';

    case LINE_ITEM = 'LINE_ITEM';

    case BET_DELIVERABLE_SERVICE = 'BET_DELIVERABLE_SERVICE';

    case CONTENT = 'CONTENT';

    case CONVERSATION = 'CONVERSATION';

    case BET_ALERT = 'BET_ALERT';

    case PORTAL = 'PORTAL';

    case QUOTE = 'QUOTE';

    case FORM_SUBMISSION_INBOUNDDB = 'FORM_SUBMISSION_INBOUNDDB';

    case QUOTA = 'QUOTA';

    case UNSUBSCRIBE = 'UNSUBSCRIBE';

    case COMMUNICATION = 'COMMUNICATION';

    case FEEDBACK_SUBMISSION = 'FEEDBACK_SUBMISSION';

    case ATTRIBUTION = 'ATTRIBUTION';

    case SALESFORCE_SYNC_ERROR = 'SALESFORCE_SYNC_ERROR';

    case RESTORABLE_CRM_OBJECT = 'RESTORABLE_CRM_OBJECT';

    case HUB = 'HUB';

    case LANDING_PAGE = 'LANDING_PAGE';

    case PRODUCT_OR_FOLDER = 'PRODUCT_OR_FOLDER';

    case TASK = 'TASK';

    case FORM = 'FORM';

    case MARKETING_EMAIL = 'MARKETING_EMAIL';

    case AD_ACCOUNT = 'AD_ACCOUNT';

    case AD_CAMPAIGN = 'AD_CAMPAIGN';

    case AD_GROUP = 'AD_GROUP';

    case AD = 'AD';

    case KEYWORD = 'KEYWORD';

    case CAMPAIGN = 'CAMPAIGN';

    case SOCIAL_CHANNEL = 'SOCIAL_CHANNEL';

    case SOCIAL_POST = 'SOCIAL_POST';

    case SITE_PAGE = 'SITE_PAGE';

    case BLOG_POST = 'BLOG_POST';

    case IMPORT = 'IMPORT';

    case EXPORT = 'EXPORT';

    case CTA = 'CTA';

    case TASK_TEMPLATE = 'TASK_TEMPLATE';

    case AUTOMATION_PLATFORM_FLOW = 'AUTOMATION_PLATFORM_FLOW';

    case OBJECT_LIST = 'OBJECT_LIST';

    case NOTE = 'NOTE';

    case MEETING_EVENT = 'MEETING_EVENT';

    case CALL = 'CALL';

    case EMAIL = 'EMAIL';

    case PUBLISHING_TASK = 'PUBLISHING_TASK';

    case CONVERSATION_SESSION = 'CONVERSATION_SESSION';

    case CONTACT_CREATE_ATTRIBUTION = 'CONTACT_CREATE_ATTRIBUTION';

    case INVOICE = 'INVOICE';

    case MARKETING_EVENT = 'MARKETING_EVENT';

    case CONVERSATION_INBOX = 'CONVERSATION_INBOX';

    case CHATFLOW = 'CHATFLOW';

    case MEDIA_BRIDGE = 'MEDIA_BRIDGE';

    case SEQUENCE = 'SEQUENCE';

    case SEQUENCE_STEP = 'SEQUENCE_STEP';

    case FORECAST = 'FORECAST';

    case SNIPPET = 'SNIPPET';

    case TEMPLATE = 'TEMPLATE';

    case DEAL_CREATE_ATTRIBUTION = 'DEAL_CREATE_ATTRIBUTION';

    case QUOTE_TEMPLATE = 'QUOTE_TEMPLATE';

    case QUOTE_MODULE = 'QUOTE_MODULE';

    case QUOTE_MODULE_FIELD = 'QUOTE_MODULE_FIELD';

    case QUOTE_FIELD = 'QUOTE_FIELD';

    case SEQUENCE_ENROLLMENT = 'SEQUENCE_ENROLLMENT';

    case SUBSCRIPTION = 'SUBSCRIPTION';

    case ACCEPTANCE_TEST = 'ACCEPTANCE_TEST';

    case SOCIAL_BROADCAST = 'SOCIAL_BROADCAST';

    case DEAL_SPLIT = 'DEAL_SPLIT';

    case DEAL_REGISTRATION = 'DEAL_REGISTRATION';

    case GOAL_TARGET = 'GOAL_TARGET';

    case GOAL_TARGET_GROUP = 'GOAL_TARGET_GROUP';

    case PORTAL_OBJECT_SYNC_MESSAGE = 'PORTAL_OBJECT_SYNC_MESSAGE';

    case FILE_MANAGER_FILE = 'FILE_MANAGER_FILE';

    case FILE_MANAGER_FOLDER = 'FILE_MANAGER_FOLDER';

    case SEQUENCE_STEP_ENROLLMENT = 'SEQUENCE_STEP_ENROLLMENT';

    case APPROVAL = 'APPROVAL';

    case APPROVAL_STEP = 'APPROVAL_STEP';

    case CTA_VARIANT = 'CTA_VARIANT';

    case SALES_DOCUMENT = 'SALES_DOCUMENT';

    case DISCOUNT = 'DISCOUNT';

    case FEE = 'FEE';

    case TAX = 'TAX';

    case MARKETING_CALENDAR = 'MARKETING_CALENDAR';

    case PERMISSIONS_TESTING = 'PERMISSIONS_TESTING';

    case PRIVACY_SCANNER_COOKIE = 'PRIVACY_SCANNER_COOKIE';

    case DATA_SYNC_STATE = 'DATA_SYNC_STATE';

    case WEB_INTERACTIVE = 'WEB_INTERACTIVE';

    case PLAYBOOK = 'PLAYBOOK';

    case FOLDER = 'FOLDER';

    case PLAYBOOK_QUESTION = 'PLAYBOOK_QUESTION';

    case PLAYBOOK_SUBMISSION = 'PLAYBOOK_SUBMISSION';

    case PLAYBOOK_SUBMISSION_ANSWER = 'PLAYBOOK_SUBMISSION_ANSWER';

    case COMMERCE_PAYMENT = 'COMMERCE_PAYMENT';

    case GSC_PROPERTY = 'GSC_PROPERTY';

    case SOX_PROTECTED_DUMMY_TYPE = 'SOX_PROTECTED_DUMMY_TYPE';

    case BLOG_LISTING_PAGE = 'BLOG_LISTING_PAGE';

    case QUARANTINED_SUBMISSION = 'QUARANTINED_SUBMISSION';

    case PAYMENT_SCHEDULE = 'PAYMENT_SCHEDULE';

    case PAYMENT_SCHEDULE_INSTALLMENT = 'PAYMENT_SCHEDULE_INSTALLMENT';

    case MARKETING_CAMPAIGN_UTM = 'MARKETING_CAMPAIGN_UTM';

    case DISCOUNT_TEMPLATE = 'DISCOUNT_TEMPLATE';

    case DISCOUNT_CODE = 'DISCOUNT_CODE';

    case FEEDBACK_SURVEY = 'FEEDBACK_SURVEY';

    case CMS_URL = 'CMS_URL';

    case SALES_TASK = 'SALES_TASK';

    case SALES_WORKLOAD = 'SALES_WORKLOAD';

    case USER = 'USER';

    case POSTAL_MAIL = 'POSTAL_MAIL';

    case SCHEMAS_BACKEND_TEST = 'SCHEMAS_BACKEND_TEST';

    case PAYMENT_LINK = 'PAYMENT_LINK';

    case SUBMISSION_TAG = 'SUBMISSION_TAG';

    case CAMPAIGN_STEP = 'CAMPAIGN_STEP';

    case SCHEDULING_PAGE = 'SCHEDULING_PAGE';

    case SOX_PROTECTED_TEST_TYPE = 'SOX_PROTECTED_TEST_TYPE';

    case ORDER = 'ORDER';

    case MARKETING_SMS = 'MARKETING_SMS';

    case PARTNER_ACCOUNT = 'PARTNER_ACCOUNT';

    case CAMPAIGN_TEMPLATE = 'CAMPAIGN_TEMPLATE';

    case CAMPAIGN_TEMPLATE_STEP = 'CAMPAIGN_TEMPLATE_STEP';

    case PLAYLIST = 'PLAYLIST';

    case CLIP = 'CLIP';

    case CAMPAIGN_BUDGET_ITEM = 'CAMPAIGN_BUDGET_ITEM';

    case CAMPAIGN_SPEND_ITEM = 'CAMPAIGN_SPEND_ITEM';

    case MIC = 'MIC';

    case CONTENT_AUDIT = 'CONTENT_AUDIT';

    case CONTENT_AUDIT_PAGE = 'CONTENT_AUDIT_PAGE';

    case PLAYLIST_FOLDER = 'PLAYLIST_FOLDER';

    case LEAD = 'LEAD';

    case ABANDONED_CART = 'ABANDONED_CART';

    case EXTERNAL_WEB_URL = 'EXTERNAL_WEB_URL';

    case VIEW = 'VIEW';

    case VIEW_BLOCK = 'VIEW_BLOCK';

    case ROSTER = 'ROSTER';

    case CART = 'CART';

    case AUTOMATION_PLATFORM_FLOW_ACTION = 'AUTOMATION_PLATFORM_FLOW_ACTION';

    case SOCIAL_PROFILE = 'SOCIAL_PROFILE';

    case PARTNER_CLIENT = 'PARTNER_CLIENT';

    case ROSTER_MEMBER = 'ROSTER_MEMBER';

    case MARKETING_EVENT_ATTENDANCE = 'MARKETING_EVENT_ATTENDANCE';

    case ALL_PAGES = 'ALL_PAGES';

    case AI_FORECAST = 'AI_FORECAST';

    case CRM_PIPELINES_DUMMY_TYPE = 'CRM_PIPELINES_DUMMY_TYPE';

    case KNOWLEDGE_ARTICLE = 'KNOWLEDGE_ARTICLE';

    case PROPERTY_INFO = 'PROPERTY_INFO';

    case DATA_PRIVACY_CONSENT = 'DATA_PRIVACY_CONSENT';

    case GOAL_TEMPLATE = 'GOAL_TEMPLATE';

    case SCORE_CONFIGURATION = 'SCORE_CONFIGURATION';

    case AUDIENCE = 'AUDIENCE';

    case PARTNER_CLIENT_REVENUE = 'PARTNER_CLIENT_REVENUE';

    case AUTOMATION_JOURNEY = 'AUTOMATION_JOURNEY';

    case UNKNOWN = 'UNKNOWN';
}
